### ISSUE TITLE
Does it support any integration with Alamofire?

### ISSUE THREAD

**Issue by goktugaral** [grandcentrix/GCXTrustPolicy#6]
Hello there,

I am trying to implement SSL pinning for my project but I couldn't manage to work on Alamofire. Can I use this with Alamofire lib. or do you have some experience? Thanks for your help!

**Comment by PaulEhrhardt** [comment]
Alamofire comes with its own SSL pinning mechanism but I think it is also possible to use GCXTrustPolicy for pinning. 
You will have to create a SSL pinning policy (e.g. Certificate/ Public Key / ... ) and perform your remote call. Then, on authentication challenge, validate the remote trust against your previously defined policy. 
Refer the readme for more details: https://github.com/grandcentrix/GCXTrustPolicy/blob/master/README.md
